# ansible-playbook get-os-version.yml
---
    - hosts: HOST-GROUP
      tasks:
      - debug:
          msg:
          - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
          - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
          - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"